version: '3'

services:
  cli:
    image: ghcr.io/maskanyone/maskanyone/cli:${MASK_ANYONE_VERSION}
    depends_on:
      - sam2
    environment:
      WORKER_LOCAL_DATA_DIR: "/worker_data"
    volumes:
      - .:/data

  sam2:
    image: ghcr.io/maskanyone/maskanyone/sam2:${MASK_ANYONE_VERSION}
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

  openpose:
    image: ghcr.io/maskanyone/maskanyone/openpose:${MASK_ANYONE_VERSION}
    restart: on-failure
    environment:
      OPENPOSE_MODEL_DIR: "/workspace/openpose/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
